# Generated by Django 4.1 on 2022-09-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=50)),
            ],
        ),
    ]
